// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySa4S1C6FzvHHzkVvl1Hb-yXtN0ICUSQ',
    appId: '1:232809362090:web:04422973a8fbbe838dd6d3',
    messagingSenderId: '232809362090',
    projectId: 'fb-counter-app',
    authDomain: 'fb-counter-app.firebaseapp.com',
    storageBucket: 'fb-counter-app.appspot.com',
    measurementId: 'G-F8KFQW1HDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmtDnktLnxuwiP9maEoAPQgXxJOIasiI',
    appId: '1:232809362090:android:0123aa1631fef9788dd6d3',
    messagingSenderId: '232809362090',
    projectId: 'fb-counter-app',
    storageBucket: 'fb-counter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmGdooJonVreRNtSrelExQm6IS2ezJ4Y',
    appId: '1:232809362090:ios:2d7b46d3c2f2a9078dd6d3',
    messagingSenderId: '232809362090',
    projectId: 'fb-counter-app',
    storageBucket: 'fb-counter-app.appspot.com',
    iosBundleId: 'com.example.counter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmGdooJonVreRNtSrelExQm6IS2ezJ4Y',
    appId: '1:232809362090:ios:2d7b46d3c2f2a9078dd6d3',
    messagingSenderId: '232809362090',
    projectId: 'fb-counter-app',
    storageBucket: 'fb-counter-app.appspot.com',
    iosBundleId: 'com.example.counter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDySa4S1C6FzvHHzkVvl1Hb-yXtN0ICUSQ',
    appId: '1:232809362090:web:6c4dfd169f51b7488dd6d3',
    messagingSenderId: '232809362090',
    projectId: 'fb-counter-app',
    authDomain: 'fb-counter-app.firebaseapp.com',
    storageBucket: 'fb-counter-app.appspot.com',
    measurementId: 'G-GQES78TCVW',
  );
}
